language: node_js
node_js:
  - "6"
  - "7"
cache: yarn
after_success:
  - test $TRAVIS_TEST_RESULT = 0 && echo "Tests Passed, building project"
  - yarn run clean && yarn run copy-assets && yarn run build:production
  - echo "Build succeeded"
